name: Trivy Hybrid Scan

on:
  push:
    branches:
      - main

jobs:
  trivy-hybrid-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Print GITHUB_RUN_ID
        run: echo "Ref name is $GITHUB_RUN_ID"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t myapp:latest .

      # Step 4: Save the Docker image as a TAR file
      - name: Save Docker image as TAR file
        run: |
          docker save -o output.tar myapp:latest
          tar -tf output.tar

      - name: Run Trivy scan
        uses: cloudbees-io/trivy-github-test@test
        with:
          binary-tar-path: output.tar
          cloudbees_pat_token: ${{ secrets.CLOUDBEES_QA_PAT }}
          cloudbees_api_url: ${{ vars.CLOUDBEES_QA_API_URL }}